test/run.sh: `set -e` in the shell which runs the tests
This will let us see how many tests are broken by that.

Optimistically, the whole test suite would work under
`set -euo pipefail` regime.

This change results in the following failures in CI status:

https://github.com/andrey-utkin/cvmfs/actions/runs/26533143259/job/78154866131

Tests:    114
Skipped:  28
Passed:   65
Warnings: 1
Failures: 20

took 10 minutes 5.438 seconds

Warnings / failures digest:
016-dnsunreachable ..... FAIL |   2.0s | retval 101
027-autoumount ......... FAIL |  21.0s | retval 2
028-negativecache ...... FAIL |   3.6s | retval 2
037-strictmount ........ FAIL |   0.7s | retval 2
041-rocache ............ FAIL |   0.9s | retval 32
042-cleanuppipes ....... FAIL |   2.2s | retval 1
054-geoapi ............. WARN |   5.9s | warning
057-parallelmakecache .. FAIL |   0.8s | retval 2
058-keysdir ............ FAIL |   3.9s | retval 101
064-fsck ............... FAIL |   7.3s | retval 1
066-killall ............ FAIL |  24.9s | retval 1
068-rocache ............ FAIL |   0.1s | retval 1
069-systemremount ...... FAIL |   2.1s | retval 32
077-doublemount ........ FAIL |   1.4s | retval 32
080-tracing ............ FAIL |   1.4s | retval 1
081-shrinkwrap ......... FAIL |  11.0s | retval 2
087-xattrs ............. FAIL |   1.1s | retval 1
095-fuser .............. FAIL |   3.1s | retval 1
102-reusefd ............ FAIL |   8.6s | retval 1
108-global-config ...... FAIL |   0.0s | retval 1
111-ignore-mount-attempt  FAIL |   1.2s | retval 32
Error: Process completed with exit code 1.

https://github.com/andrey-utkin/cvmfs/actions/runs/26533143256/job/78154866106

Tests:    2
Skipped:  0
Passed:   0
Warnings: 0
Failures: 2

took 1.211 seconds

Warnings / failures digest:
migration_tests/001-hotpatch  FAIL |   0.1s | retval 1
migration_tests/500-server_repo  FAIL |   0.3s | retval 100

https://github.com/andrey-utkin/cvmfs/actions/runs/26533143304/job/78154866323

Tests:    114
Skipped:  39
Passed:   54
Warnings: 2
Failures: 19

took 9 minutes 0.943 seconds

Warnings / failures digest:
016-dnsunreachable ..... FAIL |   3.5s | retval 101
018-httpunreachable .... WARN |  16.4s | time limit exceeded
027-autoumount ......... FAIL |  22.0s | retval 2
028-negativecache ...... FAIL |   2.6s | retval 2
037-strictmount ........ FAIL |   1.2s | retval 2
054-geoapi ............. WARN |   5.8s | warning
057-parallelmakecache .. FAIL |   0.4s | retval 2
058-keysdir ............ FAIL |   4.0s | retval 101
064-fsck ............... FAIL |   5.4s | retval 1
066-killall ............ FAIL |  20.5s | retval 1
068-rocache ............ FAIL |   0.1s | retval 1
069-systemremount ...... FAIL |   4.2s | retval 32
077-doublemount ........ FAIL |   3.2s | retval 32
080-tracing ............ FAIL |   1.7s | retval 1
086-reloadmanualmount .. FAIL |   1.3s | retval 5
087-xattrs ............. FAIL |   1.9s | retval 1
091-defaultconfigrepo .. FAIL |   1.4s | retval 2
095-fuser .............. FAIL |   3.2s | retval 1
104-concurrent_mounts .. FAIL |   8.0s | retval 1
108-global-config ...... FAIL |   0.0s | retval 1
111-ignore-mount-attempt  FAIL |   2.8s | retval 32
Error: Process completed with exit code 19.

https://github.com/andrey-utkin/cvmfs/actions/runs/26533143306/job/78154866081

Tests:    196
Skipped:  112
Passed:   70
Warnings: 0
Failures: 14

took 20 minutes 57.922 seconds

Warnings / failures digest:
500-mkrepo ............. FAIL |   4.0s | retval 17
527-publishretval ...... FAIL |   4.2s | retval 100
540-rootcvmfscatalog ... FAIL |   5.3s | retval 100
541-preloadcache ....... FAIL |   6.8s | retval 32
551-openfds ............ FAIL |  65.8s | retval 100
552-repodate ........... FAIL |  12.4s | retval 22
592-magicsymlinks ...... FAIL |   5.1s | retval 1
606-graftutil .......... FAIL |   0.1s | retval 2
611-idleclient ......... FAIL |   5.2s | retval 1
621-snapshotallgcall ... FAIL |   6.2s | retval 1
674-alienupdate ........ FAIL |   7.2s | retval 32
678-preloadautoupdate .. FAIL |  11.9s | retval 32
685-mkfs_proxy ......... FAIL |   1.2s | retval 1
689-inodes ............. FAIL |   5.9s | retval 2
Error: Process completed with exit code 14.