ci: try ubuntu-22.04
ubuntu-latest failed thus:

Run docker exec -u sftnight -t cvmfs-dev bash -c \
  docker exec -u sftnight -t cvmfs-dev bash -c \
    "cmake -S /home/sftnight/cvmfs -B /tmp/cvmfs-build -D EXTERNALS_PREFIX=/tmp/cvmfs-ext -D BUILD_SHRINKWRAP=ON"
  shell: /usr/bin/bash -e {0}
Error response from daemon: container 0145e6dcf02cecf545ecd24158611ef917921f05b5d2787f2896d016f7702a6b is not running
Error: Process completed with exit code 1.