add missing zip::
In file included from /usr/local/src/cvmfs/test/unittests/t_catalog_traversal.cc:11:
In file included from /usr/local/src/cvmfs/cvmfs/catalog_traversal.h:20:
/usr/local/src/cvmfs/cvmfs/object_fetcher.h:450:15: error: unknown type name 'Decompressor'; did you mean 'zip::Decompressor'?
  450 |     UniquePtr<Decompressor> decomp = zip::Decompressor::Construct(decomp_alg);
      |               ^~~~~~~~~~~~
      |               zip::Decompressor
/usr/local/src/cvmfs/cvmfs/compression/decompressor.h:42:7: note: 'zip::Decompressor' declared here
   42 | class Decompressor : public PolymorphicConstruction<Decompressor, Algorithms> {
      |       ^